name: QA PR

on:
  pull_request:
  pull_request_review:
    types:
      - submitted
  push:
    branches:
      - "**"
      - "!main"

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main
